# Generated by Django 4.2.13 on 2024-05-11 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания корзины')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Напишите категория', max_length=200)),
                ('descriptionCategory', models.TextField(help_text='Напишите описание категории', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(help_text='Уникальный идентификатор клиента', primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Имя клиента', max_length=50)),
                ('last_name', models.CharField(help_text='Фамилия клиента', max_length=50)),
                ('email', models.EmailField(help_text='Адрес электронной почты клиента', max_length=254)),
                ('phone', models.CharField(help_text='Номер телефона клиента', max_length=15)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок новости', max_length=200)),
                ('text', models.TextField(help_text='Введите текст новости')),
                ('pub_date', models.DateTimeField(help_text='Выберите дату и время публикации новости', verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(help_text='Уникальный ID заказа', primary_key=True, serialize=False)),
                ('order_datetime', models.DateTimeField(auto_now_add=True, help_text='Дата и время размещения заказа')),
                ('order_status', models.CharField(choices=[('новый', 'Новый'), ('в_обработке', 'В обработке'), ('выполнен', 'Выполнен')], default='новый', help_text='Статус заказа', max_length=20)),
                ('order_total', models.DecimalField(decimal_places=2, help_text='Общая сумма заказа', max_digits=10)),
                ('cart', models.ForeignKey(help_text='ID корзины', on_delete=django.db.models.deletion.CASCADE, to='catalog.cart')),
                ('client', models.ForeignKey(help_text='ID клиента', on_delete=django.db.models.deletion.CASCADE, to='catalog.client')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plant_id', models.AutoField(help_text='Уникальный идентификатор растения', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Название растения', max_length=100)),
                ('description', models.TextField(help_text='Описание растения')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена растения', max_digits=10)),
                ('availability', models.BooleanField(default=True, help_text='Наличие на складе')),
                ('image', models.ImageField(help_text='Изображение растения', upload_to='images/')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_id', models.AutoField(help_text='Уникальный идентификатор распродажи', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Название распродажи', max_length=100)),
                ('date', models.DateField(help_text='Дата проведения распродажи')),
                ('discount_percentage', models.IntegerField(help_text='Процент скидки')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(help_text='Уникальный идентификатор отзыва', primary_key=True, serialize=False)),
                ('rating', models.IntegerField(help_text='Оценка (от 1 до 5)')),
                ('text', models.TextField(help_text='Текст отзыва')),
                ('publication_date', models.DateTimeField(auto_now_add=True, help_text='Дата публикации')),
                ('client', models.ForeignKey(help_text='ID клиента', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.client')),
                ('plant', models.ForeignKey(help_text='ID растения', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.plant')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='PlantSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.ForeignKey(help_text='ID растения', on_delete=django.db.models.deletion.CASCADE, to='catalog.plant')),
                ('sale_id', models.ForeignKey(help_text='ID распродажи', on_delete=django.db.models.deletion.CASCADE, to='catalog.sale')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_amount', models.DecimalField(decimal_places=2, help_text='Сумма заказа', max_digits=10)),
                ('shipping_amount', models.DecimalField(decimal_places=2, help_text='Сумма доставки', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Итого', max_digits=10)),
                ('order', models.ForeignKey(help_text='ID заказа (внешний ключ)', on_delete=django.db.models.deletion.CASCADE, to='catalog.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Количество')),
                ('order', models.ForeignKey(help_text='ID заказа (внешний ключ)', on_delete=django.db.models.deletion.CASCADE, to='catalog.order')),
                ('plant', models.ForeignKey(help_text='ID растения (внешний ключ)', on_delete=django.db.models.deletion.CASCADE, to='catalog.plant')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('address_id', models.AutoField(help_text='Уникальный идентификатор адреса доставки', primary_key=True, serialize=False)),
                ('index', models.CharField(help_text='Индекс адреса доставки', max_length=10)),
                ('city', models.CharField(help_text='Город адреса доставки', max_length=100)),
                ('street', models.CharField(help_text='Улица адреса доставки', max_length=100)),
                ('house', models.CharField(help_text='Номер дома адреса доставки', max_length=10)),
                ('apartment', models.CharField(help_text='Номер квартиры адреса доставки', max_length=10)),
                ('client_id', models.ForeignKey(help_text='ID клиента', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_addresses', to='catalog.client')),
            ],
            options={
                'verbose_name': 'Адрес доставки',
                'verbose_name_plural': 'Адреса доставки',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_id', models.AutoField(help_text='ID доставки (первичный ключ)', primary_key=True, serialize=False)),
                ('delivery_method', models.CharField(choices=[('self_pickup', 'Самовывоз'), ('mail', 'Почта')], help_text='Способ доставки', max_length=20)),
                ('delivery_address', models.ForeignKey(blank=True, help_text='ID адреса доставки (необязательно для самовывоза)', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.deliveryaddress')),
                ('order', models.ForeignKey(help_text='ID заказа (вторичный ключ)', on_delete=django.db.models.deletion.CASCADE, to='catalog.order')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='address_id',
            field=models.ForeignKey(blank=True, help_text='ID адреса доставки', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.deliveryaddress'),
        ),
        migrations.CreateModel(
            name='CartСontent',
            fields=[
                ('cart_id', models.AutoField(help_text='ID корзины', primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(help_text='Количество растений в корзине')),
                ('plant', models.ForeignKey(help_text='ID растения', on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='catalog.plant')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_id',
            field=models.ForeignKey(help_text='ID корзины', on_delete=django.db.models.deletion.CASCADE, to='catalog.cartсontent'),
        ),
        migrations.AddField(
            model_name='cart',
            name='client',
            field=models.ForeignKey(help_text='ID клиента', on_delete=django.db.models.deletion.CASCADE, to='catalog.client'),
        ),
    ]
