# Generated by Django 4.2.13 on 2024-05-17 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='plant',
            index_together={('id', 'slug')},
        ),
    ]
